### PR TITLE
write source mapping url to target file

### PR DESCRIPTION
**Pull request by edvorg**
this will make source maps automatically discoverable in browser's dev tools

### CODE REVIEW

**Comment by edvorg** [comment]
screen shot 2018-02-16 at 8 31 38 pm
example

**Comment by yogthos** [comment]
thanks, by the way if you're interested I could add you as a maintainer to the repo

**Comment by edvorg** [comment]
@yogthos that would be great, becuase I just found a bug, but I don't want to bother you too much creating too many pull requests

**Comment by yogthos** [comment]
👍

**Comment by yogthos** [comment]
Just let me know when you'd like to do a push to Clojars and I'll do it up.

**Comment by edvorg** [comment]
Cool thanks!

**Comment by edvorg** [comment]
I think now we might cut a release if you haven't already

**Comment by yogthos** [comment]
Great,  just pushed out `0.1.4`, and thanks for the fixes. :)

**Pull request merged**
